apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bird
  name: bird-config
data:
  bird.conf: |
        /*
        *      This is a simple example configuration file with no aim for completeness.
        *      See documentation for full description.
        */

        define my_asn=65000;
        define my_addr=10.8.10.2;

        # Router ID in IPv4 format
        router id my_addr;

        # Load device information from kernel.
        protocol device {}

        # Generate direct routes for interfaces. Useful on BSD.
        protocol direct {
                ipv4;
                disabled;
        }

        protocol direct {
                ipv6;
                disabled;
        }

        # Feed routes to kernel FIB
        protocol kernel {
                ipv4 { export all; import all; };
                learn;                  # Learn all routes from the kernel
        #       scan time 10;           # Scan kernel tables every 10 seconds
        }

        protocol kernel {
                ipv6 { import all; };
                learn;
        }

        # Static route feed
        protocol static {
                ipv4 { export all; };
        }

        protocol static {
                ipv6 { export all; };
        }

        protocol rip {
                ipv4;
        }

        protocol rip ng {
                ipv6;
        }

        template bgp TEMPLATE_BGP {
                debug { states, events };
                description "IXNFO_COM";
                local my_addr as my_asn;

                ipv4 {
                        import all;
                        export all;
                };
        }

        protocol bgp uplink0 from TEMPLATE_BGP {
                neighbor 10.8.10.41 as 65200;
        }

        protocol bgp uplink1 from TEMPLATE_BGP {
                neighbor 10.8.10.42 as 65200;
        }
